<?php

namespace Database\Factories;

use App\Models\Review;
use App\Models\User;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

class ReviewFactory extends Factory
{
    protected $model = Review::class;

    public function definition(): array
    {
        return [
            // Attach to an existing random user if present, otherwise create one
            'user_id' => User::inRandomOrder()->first()->id ?? User::factory(),

            // Attach to an existing random product if present, otherwise create one
            'product_id' => Product::inRandomOrder()->first()->id ?? Product::factory(),

            // Short review body generated by Faker
            'body' => $this->faker->sentence(12),

            // Rating between 1 and 5 (inclusive)
            'rating' => $this->faker->numberBetween(1, 5),
        ];
    }
}